version: "3"
services:
  loany_db:
    image: postgres:9.6-alpine
    container_name: loany_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loany_dev
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - /var/lib/postgresql/data
#    networks:
#      - local
    ports:
      - 5432:5432
  loany_app:
    build: .
    container_name: loany_app
#    command: mix phx.server
    command: iex -S mix phx.server
    environment:
      - MIX_ENV=dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 4000:4000
#    networks:
#      - local
    depends_on:
      - loany_db
#  networks:
#    local:
#      driver:
#        bridge
#  volumes:
#    db:
#      driver:
#        local
